version: "3"
services:
  api:
    build: .
    depends_on:
      - postgres
    ports:
      - 8000:8000
    volumes:
      - ./:/usr/src/app:ro
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    # env_file:
    #   - ./env
    environment:
      - DATABASE_HOSTNAME=localhost
      - DATABASE_PORT=5432
      - DATABASE_PASSWORD=password1234
      - DATABASE_NAME=fastapi
      - DATABASE_USERNAME=postgres
      - SECRET_KEY=jnjko38738unb3434y4335968b6kmnbv45jhbn4556njkbjbdnf
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=120
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=password1234
      - POSTGRES_DB=fastapi

    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db:
