"""add phone number

Revision ID: 17875c039ff2
Revises: 610d7f3da3d9
Create Date: 2022-12-20 15:18:16.988286

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17875c039ff2'
down_revision = '610d7f3da3d9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column(
        'phone_number', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phone_number')
    # ### end Alembic commands ###
